version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: cfo_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cfo_saas_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: cfo_mysql_adminer
    ports:
      - "8082:8080"
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql_data:
